CREATE TABLE students(

id INT AUTO_INCREMENT PRIMARY KEY,

student_id VARCHAR(30) NOT NULL UNIQUE,

name VARCHAR(100) NOT NULL,

department VARCHAR(100) NOT NULL,

semester VARCHAR(20) NOT NULL,

email VARCHAR(100),

phone VARCHAR(20),

photo VARCHAR(255),

created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);
